version: '3'
volumes:
  movies:
    external: true
  series:
    external: true
  organizr_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  portainer_data:
    labels:
      com.github.rickshinners.piratebox.backups: 'yes'
  transmission_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  transmission_downloads:
  transmission_watch:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  transmission_completed:
  nzbget_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  nzbget_downloads:
  nzbget_completed:
  sonarr_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  radarr_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  plex_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  plex_transcode:
  plexpy_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
  ombi_config:
    labels:
      com.github.rickshinners.piratebox.backup: 'yes'
services:
  traefik:
    image: traefik
    command: --api --docker --docker.watch --docker.domain=${DOMAIN} --acme.domains=${DOMAIN}
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml
      - ./traefik/.htpasswd:/etc/traefik/.htpasswd:ro
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_REGION
      - AWS_HOSTED_ZONE_ID
    labels:
      traefik.enable: "true"
      traefik.frontend.rule: "Host:monitor.${DOMAIN}"
      traefik.port: "8080"
      com.centurylinklabs.watchtower.enable: "true"
    restart: always
  watchtower:
    image: v2tec/watchtower
    command: --cleanup --label-enable --schedule="0 0 5 * * *"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  update-dns:
    image: rickshinners/dns-updater
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_HOSTED_ZONE_ID
      - DNS_NAME
      - CRON=*/30 * * * *
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    restart: unless-stopped
  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:portainer.${DOMAIN}"
      traefik.port: "9000"
    restart: unless-stopped
  glances:
    image: nicolargo/glances
    ports:
      - 61208-61209:61208-61209
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    pid: host
    environment:
      - GLANCES_OPT=-w
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:glances.${DOMAIN}"
      traefik.port: "61208"
    restart: unless-stopped
  organizr:
    image: lsiocommunity/organizr
    volumes:
      - organizr_config:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${DOMAIN}"
      traefik.port: "80"
    restart: unless-stopped
  transmission:
    image: linuxserver/transmission
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    volumes:
      - transmission_config:/config
      - transmission_downloads:/downloads
      - transmission_watch:/watch
      - transmission_completed:/downloads/complete
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:transmission.${DOMAIN}"
      traefik.port: "9091"
    restart: unless-stopped
  nzbget:
    image: linuxserver/nzbget
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 6789:6789
    volumes:
      - nzbget_config:/config
      - nzbget_downloads:/downloads
      - nzbget_completed:/downloads/completed
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:nzbget.${DOMAIN}"
      traefik.port: "6789"
    restart: unless-stopped
  sonarr:
    image: linuxserver/sonarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8989:8989
    volumes:
      - sonarr_config:/config
      - series:/tv
      - nzbget_completed:/downloads/nzbget_completed
      - transmission_completed:/downloads/transmission_completed
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:sonarr.${DOMAIN}"
      traefik.port: "8989"
    restart: unless-stopped
  radarr:
    image: linuxserver/radarr
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 7878:7878
    volumes:
      - radarr_config:/config
      - movies:/media/movies
      - nzbget_completed:/downloads/nzbget_completed
      - transmission_completed:/downloads/transmission_completed
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:radarr.${DOMAIN}"
      traefik.port: "7878"
    restart: unless-stopped
  plex:
    image: linuxserver/plex
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - VERSION=latest
    network_mode: host
    volumes:
      - plex_config:/config
      - series:/data/tvshows:ro
      - movies:/data/movies:ro
      - plex_transcode:/transcode
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:plex.${DOMAIN}"
      traefik.port: "32400"
    restart: unless-stopped
  plexpy:
    image: linuxserver/plexpy
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8181:8181
    volumes:
      - plex_config:/logs:ro
      - plexpy_config:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:plexpy.${DOMAIN}"
      traefik.port: "8181"
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    environment:
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 3579:3579
    volumes:
      - ombi_config:/config
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:ombi.${DOMAIN}"
      traefik.port: "3579"
    restart: unless-stopped
  netdata:
    image: titpetric/netdata
    ports:
      - 19999:19999
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/host/var/run/docker.sock:ro
      - ./netdata/netdata.conf:/etc/netdata/override/netdata.conf:ro
    cap_add:
      - SYS_PTRACE
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:netdata.${DOMAIN}"
      traefik.port: "19999"
    restart: unless-stopped